#' Get Swiss Accounting Plan Template
#'
#' Returns a tibble containing the Swiss accounting plan (Kontenrahmen KMU)
#' with account numbers, descriptions, and account types. The accounting plan
#' follows the Swiss standard chart of accounts for small and medium-sized
#' enterprises.
#'
#' @param language A character string specifying the language of the account
#'   descriptions. Must be one of `"fr"` (French), `"de"` (German), or `"en"`
#'
#' @returns A tibble with the following columns:
#'
#'   * `account_number`: Integer. The account number according to the Swiss
#'     accounting plan.
#'   * `account_description`: Character. The description of the account in the
#'     specified language.
#'   * `account_type`: Character. The type of account (e.g., "Asset",
#'     "Liability", "Income", "Expense").
#'
#' @examples
#' # Get the French accounting plan
#' get_accounting_plan_template("fr")
#'
#' # Get the German accounting plan
#' get_accounting_plan_template("de")
#'
#' # Get the English accounting plan
#' get_accounting_plan_template("en")
#'
#' @export
get_accounting_plan_template <- function(language) {
  if (language == "fr") {
    tibble::tribble(
      ~account_number, ~account_description,                                                                                      ~account_type,
      1,               "Actif",                                                                                                   "Actif",
      10,              "Actifs circulants",                                                                                       "Actif",
      100,             "Liquidit\U{E9}s",                                                                                         "Actif",
      1000,            "Caisse",                                                                                                  "Actif",
      1020,            "Banque",                                                                                                  "Actif",
      106,             "Avoirs \U{E0} court terme cot\U{E9}s en bourse",                                                          "Actif",
      1060,            "Titres",                                                                                                  "Actif",
      1069,            "Ajustement de la valeur des titres",                                                                      "Actif",
      110,             "Cr\U{E9}ances r\U{E9}sultant de livraisons et prestations",                                               "Actif",
      1100,            "Cr\U{E9}ances provenant de livraisons et de prestations",                                                 "Actif",
      1109,            "Ducroire",                                                                                                "Actif",
      1110,            "Cr\U{E9}ances r\U{E9}sultant de livraisons et prestations envers les soci\U{E9}t\U{E9}s du groupe",       "Actif",
      114,             "Autres cr\U{E9}ances \U{E0} court terme",                                                                 "Actif",
      1140,            "Avances et pr\U{EA}ts",                                                                                   "Actif",
      1149,            "Ajustement de la valeur des avances et des pr\U{EA}ts",                                                   "Actif",
      1170,            "Imp\U{F4}t pr\U{E9}alable : TVA s/mat\U{E9}riel, marchandises, prestations et \U{E9}nergie",              "Actif",
      1171,            "Imp\U{F4}t pr\U{E9}alable : TVA s/investissements et autres charges d'exploitation",                      "Actif",
      1176,            "Imp\U{F4}t anticip\U{E9}",                                                                                "Actif",
      1180,            "Cr\U{E9}ances envers les assurances sociales et institutions de pr\U{E9}voyance",                         "Actif",
      1189,            "Imp\U{F4}t \U{E0} la source",                                                                             "Actif",
      1190,            "Autres cr\U{E9}ances \U{E0} court terme",                                                                 "Actif",
      1199,            "Ajustement de la valeur des cr\U{E9}ances \U{E0} court terme",                                            "Actif",
      120,             "Stocks et prestations non factur\U{E9}es",                                                                "Actif",
      1200,            "Marchandises commerciales",                                                                               "Actif",
      1210,            "Mati\U{E8}res premi\U{E8}res",                                                                            "Actif",
      1220,            "Mati\U{E8}res auxiliaires",                                                                               "Actif",
      1230,            "Mati\U{E8}res consommables",                                                                              "Actif",
      1250,            "Marchandises en consignation",                                                                            "Actif",
      1260,            "Stocks de produits finis",                                                                                "Actif",
      1280,            "Travaux en cours",                                                                                        "Actif",
      130,             "Compte de r\U{E9}gularisation de l'actif",                                                                "Actif",
      1300,            "Charges pay\U{E9}es d'avance",                                                                            "Actif",
      1301,            "Produits \U{E0} recevoir",                                                                                "Actif",
      14,              "Actifs immobilis\U{E9}s",                                                                                 "Actif",
      140,             "Immobilisations financi\U{E8}res",                                                                        "Actif",
      1400,            "Titres \U{E0} long terme",                                                                                "Actif",
      1409,            "Ajustement de la valeur des titres",                                                                      "Actif",
      1440,            "Pr\U{EA}ts",                                                                                              "Actif",
      1441,            "Hypoth\U{E8}ques",                                                                                        "Actif",
      1449,            "Ajustement de la valeur des cr\U{E9}ances \U{E0} long terme",                                             "Actif",
      148,             "Participations",                                                                                          "Actif",
      1480,            "Participations",                                                                                          "Actif",
      1489,            "Ajustement de la valeur des participations",                                                              "Actif",
      150,             "Immobilisations corporelles meubles",                                                                     "Actif",
      1500,            "Machines et appareils",                                                                                   "Actif",
      1509,            "Ajustement de la valeur des machines et appareils",                                                       "Actif",
      1510,            "Mobilier et installations",                                                                               "Actif",
      1519,            "Ajustement de la valeur du mobilier et des installations",                                                "Actif",
      1520,            "Machines de bureau, informatique, syst\U{E8}mes de communication",                                        "Actif",
      1529,            "Ajustement de la valeur des machines de bureau, inf. et syst. comm.",                                     "Actif",
      1530,            "V\U{E9}hicules",                                                                                          "Actif",
      1539,            "Ajustement de la valeur des v\U{E9}hicules",                                                              "Actif",
      1540,            "Outillages et appareils",                                                                                 "Actif",
      1549,            "Ajustement de la valeur des outillages et appareils",                                                     "Actif",
      160,             "Immobilisations corporelles immeubles",                                                                   "Actif",
      1600,            "Immeubles d'exploitation",                                                                                "Actif",
      1609,            "Ajustement de la valeur des immeubles d'exploitation",                                                    "Actif",
      170,             "Immobilisations incorporelles",                                                                           "Actif",
      1700,            "Brevets, know-how, licences, droits, d\U{E9}veloppement",                                                 "Actif",
      1709,            "Ajustement de la valeur des brevets, know-how, licences, droits, d\U{E9}v.",                              "Actif",
      1770,            "Goodwill",                                                                                                "Actif",
      1779,            "Ajustement de la valeur des goodwill",                                                                    "Actif",
      180,             "Capital non vers\U{E9} : capital social, capital de fondation",                                           "Actif",
      1850,            "Capital actions, capital social, droits de participations ou capital de fondation non vers\U{E9}s",       "Actif",
      2,               "Passif",                                                                                                  "Passif",
      20,              "Dettes \U{E0} court terme",                                                                               "Passif",
      200,             "Dettes \U{E0} court terme r\U{E9}sultant d'achats et de prestations de services",                         "Passif",
      2000,            "Dettes r\U{E9}sultant d'achats et de prestation de services (cr\U{E9}anciers)",                           "Passif",
      2030,            "Acomptes de clients",                                                                                     "Passif",
      2050,            "Dettes r\U{E9}sultant d'achats et de prestations de services envers des soci\U{E9}t\U{E9}s du groupe",    "Passif",
      210,             "Dettes \U{E0} court terme r\U{E9}mun\U{E9}r\U{E9}s",                                                      "Passif",
      2100,            "Dettes bancaires",                                                                                        "Passif",
      2120,            "Engagements de financement par leasing",                                                                  "Passif",
      2140,            "Autres dettes \U{E0} court terme r\U{E9}mun\U{E9}r\U{E9}es",                                              "Passif",
      220,             "Autres dettes \U{E0} court terme",                                                                        "Passif",
      2200,            "TVA due",                                                                                                 "Passif",
      2201,            "D\U{E9}compte TVA",                                                                                       "Passif",
      2206,            "Imp\U{F4}t anticip\U{E9} d\U{FB}",                                                                        "Passif",
      2208,            "Imp\U{F4}ts directs",                                                                                     "Passif",
      2210,            "Autres dettes \U{E0} court terme",                                                                        "Passif",
      2261,            "Dividendes",                                                                                              "Passif",
      2270,            "Assurances sociales et institutions de pr\U{E9}voyance",                                                  "Passif",
      2279,            "Imp\U{F4}t \U{E0} la source",                                                                             "Passif",
      230,             "Passifs de r\U{E9}gularisation et provisions \U{E0} court terme",                                         "Passif",
      2300,            "Charges \U{E0} payer",                                                                                    "Passif",
      2301,            "Produits encaiss\U{E9}s d'avance",                                                                        "Passif",
      2330,            "Provisions \U{E0} court terme",                                                                           "Passif",
      24,              "Dettes \U{E0} long terme",                                                                                "Passif",
      240,             "Dettes \U{E0} long terme r\U{E9}mun\U{E9}r\U{E9}es",                                                      "Passif",
      2400,            "Dettes bancaires",                                                                                        "Passif",
      2420,            "Engagements de financement par leasing",                                                                  "Passif",
      2430,            "Emprunts obligataires",                                                                                   "Passif",
      2450,            "Emprunts",                                                                                                "Passif",
      2451,            "Hypoth\U{E8}ques",                                                                                        "Passif",
      250,             "Autres dettes \U{E0} long terme",                                                                         "Passif",
      2500,            "Autres dettes \U{E0} long terme",                                                                         "Passif",
      260,             "Provisions \U{E0} long termes et provisions l\U{E9}gales",                                                "Passif",
      2600,            "Provisions",                                                                                              "Passif",
      28,              "Fonds propres (personnes morales)",                                                                       "Passif",
      280,             "Capital social ou capital de fondation",                                                                  "Passif",
      2800,            "Capital-actions, capital social, capital de fondation",                                                   "Passif",
      290,             "R\U{E9}serves / b\U{E9}n\U{E9}fices et pertes",                                                           "Passif",
      2900,            "R\U{E9}serves l\U{E9}gales issues du capital",                                                            "Passif",
      2930,            "R\U{E9}serves sur participations propres au capital",                                                     "Passif",
      2940,            "R\U{E9}serves d'\U{E9}valuation",                                                                         "Passif",
      2950,            "R\U{E9}serves l\U{E9}gales issues du b\U{E9}n\U{E9}fice",                                                 "Passif",
      2960,            "R\U{E9}serves libres",                                                                                    "Passif",
      2970,            "B\U{E9}n\U{E9}fice / perte report\U{E9}",                                                                 "Passif",
      2979,            "B\U{E9}n\U{E9}fice / perte de l'exercice",                                                                "Passif",
      2980,            "Propres actions, parts sociales, droits de participations (poste n\U{E9}gatif)",                          "Passif",
      2820,            "Apports de capital / pr\U{E9}l\U{E8}vements sur capital",                                                 "Passif",
      2850,            "Compte priv\U{E9}",                                                                                       "Passif",
      2891,            "B\U{E9}n\U{E9}fice / perte de l'exercice",                                                                "Passif",
      3,               "Chiffre d'affaires r\U{E9}sultant des ventes et des prestations de services",                             "Produit",
      3000,            "Ventes de produits fabriqu\U{E9}s",                                                                       "Produit",
      3200,            "Ventes de marchandises",                                                                                  "Produit",
      3400,            "Ventes de prestations",                                                                                   "Produit",
      3600,            "Autres ventes et prestations de services",                                                                "Produit",
      3700,            "Prestations propres",                                                                                     "Produit",
      3710,            "Consommations propres",                                                                                   "Produit",
      3800,            "D\U{E9}ductions sur ventes",                                                                              "Charge",
      3805,            "Pertes sur clients, variation du ducroire",                                                               "Charge",
      3900,            "Variation des stocks de produits semi-finis",                                                             "Produit/Charge",
      3901,            "Variation des stocks de produits finis",                                                                  "Produit/Charge",
      3940,            "Variation de la valeur des prestations non factur\U{E9}es",                                               "Produit/Charge",
      4,               "Charges de mat\U{E9}riel, de marchandises et de prestations de tiers",                                    "Charge",
      4000,            "Achats de mat\U{E9}riel",                                                                                 "Charge",
      4200,            "Achats de marchandises",                                                                                  "Charge",
      4400,            "Prestations / travaux de tiers",                                                                          "Charge",
      4500,            "Charges d'\U{E9}nergie pour l'exploitation",                                                              "Charge",
      4900,            "D\U{E9}ductions sur les charges",                                                                         "Produit",
      5,               "Charges de personnel",                                                                                    "Charge",
      5000,            "Salaires",                                                                                                "Charge",
      5700,            "Charges sociales",                                                                                        "Charge",
      5800,            "Autres charges de personnel",                                                                             "Charge",
      5900,            "Charges de personnels temporaires",                                                                       "Charge",
      6,               "Autres charges d'exploitation, amortissements, r\U{E9}sultat financier",                                  "Charge",
      6000,            "Charges de locaux",                                                                                       "Charge",
      6100,            "Entretien, r\U{E9}parations et remplacement des installations servant \U{E0} l'exploitation",             "Charge",
      6105,            "Leasing immobilisations corporelles meubles",                                                             "Charge",
      6200,            "Charges de v\U{E9}hicules et de transport",                                                               "Charge",
      6260,            "Leasing et location de v\U{E9}hicules",                                                                   "Charge",
      6300,            "Assurances-choses, droits, taxes, autorisations",                                                         "Charge",
      6400,            "Charges d'\U{E9}nergie et \U{E9}vacuation des d\U{E9}chets",                                              "Charge",
      6500,            "Charges d'administration",                                                                                "Charge",
      6570,            "Charges et leasing d'informatique",                                                                       "Charge",
      6600,            "Publicit\U{E9} et marketing",                                                                             "Charge",
      6700,            "Autres charges d'exploitation",                                                                           "Charge",
      6800,            "Amortissement et ajustement de valeur des postes sur immobilisations corporelles",                        "Charge",
      6900,            "Charges financi\U{E8}res",                                                                                "Charge",
      6950,            "Produits financiers",                                                                                     "Produit/Charge",
      7,               "R\U{E9}sultat des activit\U{E9}s annexes",                                                                "Produit/Charge",
      7000,            "Produits  accessoires",                                                                                   "Produit",
      7010,            "Charges  accessoires",                                                                                    "Charge",
      7500,            "Produits des immeubles d'exploitation",                                                                   "Produit",
      7510,            "Charges des immeubles d'exploitation",                                                                    "Charge",
      8,               "R\U{E9}sultats extraordinaires et hors exploitation",                                                     "Produit/Charge",
      8000,            "Charges hors exploitation",                                                                               "Charge",
      8100,            "Produits hors exploitation",                                                                              "Produit",
      8500,            "Charges extraordinaires, exceptionnelles ou hors p\U{E9}riode",                                           "Charge",
      8510,            "Produits extraordinaires, exceptionnels ou hors p\U{E9}riode",                                            "Produit",
      8900,            "Imp\U{F4}ts directs",                                                                                     "Charge",
      9,               "Cl\U{F4}ture",                                                                                            "Cl\U{F4}ture",
      91,              "Ouverture",                                                                                               "Cl\U{F4}ture",
      9100,            "Bilan d'ouverture",                                                                                       "Cl\U{F4}ture",
      92,              "B\U{E9}n\U{E9}fice / perte",                                                                              "Cl\U{F4}ture",
      9200,            "B\U{E9}n\U{E9}fice / perte de l'exercice",                                                                "Produit/Charge",
    ) |>
      ensure_type(
        account_number = integer(),
        .default = character()
      )
  } else if (language == "de") {
    tibble::tribble(
      ~account_number, ~account_description,                                                                                 ~account_type,
      1,               "Aktiva",                                                                                             "Aktivkonto",
      10,              "Umlaufverm\U{F6}gen",                                                                                "Aktivkonto",
      100,             "Kasse und Bank",                                                                                     "Aktivkonto",
      1000,            "Kasse",                                                                                              "Aktivkonto",
      1020,            "Bank",                                                                                               "Aktivkonto",
      106,             "Kurzfristig an der B\U{F6}rse notierte Wertpapiere",                                                 "Aktivkonto",
      1060,            "Wertpapiere",                                                                                        "Aktivkonto",
      1069,            "Anpassung des Wertes von Wertpapieren",                                                              "Aktivkonto",
      110,             "Forderungen aus Lieferungen und Leistungen",                                                         "Aktivkonto",
      1100,            "Forderungen aus Lieferungen und Leistungen",                                                         "Aktivkonto",
      1109,            "Wertberichtigung auf Forderungen",                                                                   "Aktivkonto",
      1110,            "Forderungen aus Lieferungen und Leistungen an verbundene Unternehmen",                               "Aktivkonto",
      114,             "Sonstige kurzfristige Forderungen",                                                                  "Aktivkonto",
      1140,            "Vorsch\U{FC}sse und Darlehen",                                                                       "Aktivkonto",
      1149,            "Anpassung des Wertes von Vorsch\U{FC}ssen und Darlehen",                                             "Aktivkonto",
      1170,            "Vorausbezahlte Steuern: MwSt auf Anlagen, Waren, Dienstleistungen und Energie",                      "Aktivkonto",
      1171,            "Vorausbezahlte Steuern: MwSt auf Investitionen und sonstige Betriebskosten",                         "Aktivkonto",
      1176,            "Antizipierte Steuern",                                                                               "Aktivkonto",
      1180,            "Forderungen gegen\U{FC}ber Sozialversicherungen und Vorsorgeeinrichtungen",                          "Aktivkonto",
      1189,            "Quellensteuer",                                                                                      "Aktivkonto",
      1190,            "Sonstige kurzfristige Forderungen",                                                                  "Aktivkonto",
      1199,            "Anpassung des Wertes von kurzfristigen Forderungen",                                                 "Aktivkonto",
      120,             "Best\U{E4}nde und nicht fakturierte Leistungen",                                                     "Aktivkonto",
      1200,            "Handelswaren",                                                                                       "Aktivkonto",
      1210,            "Rohstoffe",                                                                                          "Aktivkonto",
      1220,            "Hilfsstoffe",                                                                                        "Aktivkonto",
      1230,            "Verbrauchsmaterial",                                                                                 "Aktivkonto",
      1250,            "Waren in Kommission",                                                                                "Aktivkonto",
      1260,            "Bestand an fertigen Produkten",                                                                      "Aktivkonto",
      1280,            "Arbeiten in Bearbeitung",                                                                            "Aktivkonto",
      130,             "Kontenabstimmung f\U{FC}r Aktiva",                                                                   "Aktivkonto",
      1300,            "Vorausbezahlte Kosten",                                                                              "Aktivkonto",
      1301,            "Noch zu erhaltende Einnahmen",                                                                       "Aktivkonto",
      14,              "Immaterielle Verm\U{F6}genswerte",                                                                   "Aktivkonto",
      140,             "Finanzanlagen",                                                                                      "Aktivkonto",
      1400,            "Langfristige Wertpapiere",                                                                           "Aktivkonto",
      1409,            "Anpassung des Wertes von Langfristigen Wertpapieren",                                                "Aktivkonto",
      1440,            "Darlehen",                                                                                           "Aktivkonto",
      1441,            "Hypotheken",                                                                                         "Aktivkonto",
      1449,            "Anpassung des Wertes von Langfristigen Forderungen",                                                 "Aktivkonto",
      148,             "Beteiligungen",                                                                                      "Aktivkonto",
      1480,            "Beteiligungen",                                                                                      "Aktivkonto",
      1489,            "Anpassung des Wertes von Beteiligungen",                                                             "Aktivkonto",
      150,             "Sachanlagen beweglich",                                                                              "Aktivkonto",
      1500,            "Maschinen und Ger\U{E4}te",                                                                          "Aktivkonto",
      1509,            "Anpassung des Wertes von Maschinen und Ger\U{E4}ten",                                                "Aktivkonto",
      1510,            "M\U{F6}bel und Einrichtungen",                                                                       "Aktivkonto",
      1519,            "Anpassung des Wertes von M\U{F6}beln und Einrichtungen",                                             "Aktivkonto",
      1520,            "B\U{FC}romaschinen, Computer, Kommunikationssysteme",                                                "Aktivkonto",
      1529,            "Anpassung des Wertes von B\U{FC}romaschinen, Computern, Kommunikationssystemen",                     "Aktivkonto",
      1530,            "Fahrzeuge",                                                                                          "Aktivkonto",
      1539,            "Anpassung des Wertes von Fahrzeugen",                                                                "Aktivkonto",
      1540,            "Werkzeuge und Ger\U{E4}te",                                                                          "Aktivkonto",
      1549,            "Anpassung des Wertes von Werkzeugen und Ger\U{E4}ten",                                               "Aktivkonto",
      160,             "Sachanlagen unbeweglich",                                                                            "Aktivkonto",
      1600,            "Betriebsliegenschaften",                                                                             "Aktivkonto",
      1609,            "Anpassung des Wertes von Betriebsliegenschaften",                                                    "Aktivkonto",
      170,             "Immaterielle Verm\U{F6}genswerte",                                                                   "Aktivkonto",
      1700,            "Patente, Know-how, Lizenzen, Rechte, Entwicklung",                                                   "Aktivkonto",
      1709,            "Anpassung des Wertes von Patenten, Know-how, Lizenzen, Rechten, Entwicklung",                        "Aktivkonto",
      1770,            "Firmenwert",                                                                                         "Aktivkonto",
      1779,            "Anpassung des Wertes von Firmenwerten",                                                              "Aktivkonto",
      180,             "Nicht eingezahltes Kapital: Aktienkapital, Stiftungskapital",                                        "Aktivkonto",
      1850,            "Nicht eingezahltes Aktienkapital, Aktienkapital, Beteiligungsrechte oder Stiftungskapital",          "Aktivkonto",
      2,               "Passiva",                                                                                            "Passivkonto",
      20,              "Kurzfristige Verbindlichkeiten",                                                                     "Passivkonto",
      200,             "Kurzfristige Verbindlichkeiten aus Eink\U{E4}ufen und Dienstleistungen",                             "Passivkonto",
      2000,            "Verbindlichkeiten aus Eink\U{E4}ufen und Dienstleistungen (Kreditoren)",                             "Passivkonto",
      2030,            "Vorauszahlungen von Kunden",                                                                         "Passivkonto",
      2050,            "Verbindlichkeiten aus Eink\U{E4}ufen und Dienstleistungen gegen\U{FC}ber verbundenen Unternehmen",   "Passivkonto",
      210,             "Kurzfristig verzinsliche Verbindlichkeiten",                                                         "Passivkonto",
      2100,            "Bankverbindlichkeiten",                                                                              "Passivkonto",
      2120,            "Leasingfinanzierungspflichten",                                                                      "Passivkonto",
      2140,            "Andere kurzfristig verzinsliche Verbindlichkeiten",                                                  "Passivkonto",
      220,             "Andere kurzfristige Verbindlichkeiten",                                                              "Passivkonto",
      2200,            "MwSt-Schuld",                                                                                        "Passivkonto",
      2201,            "MwSt-Abrechnung",                                                                                    "Passivkonto",
      2206,            "Antizipierte Steuerschuld",                                                                          "Passivkonto",
      2208,            "Direkte Steuern",                                                                                    "Passivkonto",
      2210,            "Andere kurzfristige Verbindlichkeiten",                                                              "Passivkonto",
      2261,            "Dividenden",                                                                                         "Passivkonto",
      2270,            "Sozialversicherungsbeitr\U{E4}ge und Vorsorgeeinrichtungen",                                         "Passivkonto",
      2279,            "Quellensteuer",                                                                                      "Passivkonto",
      230,             "Langfristige Abgrenzungen und R\U{FC}ckstellungen",                                                  "Passivkonto",
      2300,            "Ausstehende Kosten",                                                                                 "Passivkonto",
      2301,            "Vorausbezahlte Einnahmen",                                                                           "Passivkonto",
      2330,            "Langfristige R\U{FC}ckstellungen",                                                                   "Passivkonto",
      24,              "Langfristige Verbindlichkeiten",                                                                     "Passivkonto",
      240,             "Langfristig verzinsliche Verbindlichkeiten",                                                         "Passivkonto",
      2400,            "Bankverbindlichkeiten",                                                                              "Passivkonto",
      2420,            "Leasingfinanzierungspflichten",                                                                      "Passivkonto",
      2430,            "Obligationenanleihen",                                                                               "Passivkonto",
      2450,            "Kredite",                                                                                            "Passivkonto",
      2451,            "Hypotheken",                                                                                         "Passivkonto",
      250,             "Andere langfristige Verbindlichkeiten",                                                              "Passivkonto",
      2500,            "Andere langfristige Verbindlichkeiten",                                                              "Passivkonto",
      260,             "Langfristige R\U{FC}ckstellungen und gesetzliche R\U{FC}ckstellungen",                               "Passivkonto",
      2600,            "R\U{FC}ckstellungen",                                                                                "Passivkonto",
      28,              "Eigenkapital (juristische Personen)",                                                                "Passivkonto",
      280,             "Aktienkapital oder Stiftungskapital",                                                                "Passivkonto",
      2800,            "Aktienkapital, Aktienkapital, Stiftungskapital",                                                     "Passivkonto",
      290,             "Reserven / Gewinne und Verluste",                                                                    "Passivkonto",
      2900,            "Gesetzliche Reserven aus dem Kapital",                                                               "Passivkonto",
      2930,            "Reserven auf eigene Beteiligungen am Kapital",                                                       "Passivkonto",
      2940,            "Bewertungsreserven",                                                                                 "Passivkonto",
      2950,            "Gesetzliche Reserven aus dem Gewinn",                                                                "Passivkonto",
      2960,            "Freie Reserven",                                                                                     "Passivkonto",
      2970,            "Vortragener Gewinn / Verlust",                                                                       "Passivkonto",
      2979,            "Gewinn / Verlust des Gesch\U{E4}ftsjahres",                                                          "Passivkonto",
      2980,            "Eigene Aktien, Anteile, Beteiligungsrechte (negativer Posten)",                                      "Passivkonto",
      2820,            "Kapitalzuf\U{FC}hrungen / Entnahmen",                                                                "Passivkonto",
      2850,            "Privatkonto",                                                                                        "Passivkonto",
      2891,            "Gewinn / Verlust des Gesch\U{E4}ftsjahres",                                                          "Passivkonto",
      3,               "Umsatz aus Verk\U{E4}ufen und Dienstleistungen",                                                     "Einnahmen",
      3000,            "Verk\U{E4}ufe von hergestellten Produkten",                                                          "Einnahmen",
      3200,            "Verk\U{E4}ufe von Waren",                                                                            "Einnahmen",
      3400,            "Verk\U{E4}ufe von Dienstleistungen",                                                                 "Einnahmen",
      3600,            "Andere Verk\U{E4}ufe und Dienstleistungseinnahmen",                                                  "Einnahmen",
      3700,            "Eigene Dienstleistungen",                                                                            "Einnahmen",
      3710,            "Eigener Verbrauch",                                                                                  "Einnahmen",
      3800,            "Verkaufsabz\U{FC}ge",                                                                                "Ausgabe",
      3805,            "Verluste bei Kunden, \U{C4}nderung der Kreditw\U{FC}rdigkeit",                                       "Ausgabe",
      3900,            "\U{C4}nderung des Bestands an halbfertigen Erzeugnissen",                                            "Einnahmen/Ausgabe",
      3901,            "\U{C4}nderung des Bestands an fertigen Erzeugnissen",                                                "Einnahmen/Ausgabe",
      3940,            "\U{C4}nderung des Werts unberechneter Dienstleistungen",                                             "Einnahmen/Ausgabe",
      4,               "Ausgaben f\U{FC}r Material, Waren und Dienstleistungen von Dritten",                                 "Ausgabe",
      4000,            "Materialk\U{E4}ufe",                                                                                 "Ausgabe",
      4200,            "Warenk\U{E4}ufe",                                                                                    "Ausgabe",
      4400,            "Dienstleistungen / Arbeiten von Dritten",                                                            "Ausgabe",
      4500,            "Energiekosten f\U{FC}r den Betrieb",                                                                 "Ausgabe",
      4900,            "Abz\U{FC}ge bei den Ausgaben",                                                                       "Einnahmen",
      5,               "Personalaufwendungen",                                                                               "Ausgabe",
      5000,            "L\U{F6}hne",                                                                                         "Ausgabe",
      5700,            "Sozialversicherungsbeitr\U{E4}ge",                                                                   "Ausgabe",
      5800,            "Andere Personalaufwendungen",                                                                        "Ausgabe",
      5900,            "Kosten f\U{FC}r tempor\U{E4}re Mitarbeiter",                                                         "Ausgabe",
      6,               "Andere Betriebskosten, Abschreibungen, Finanzergebnis",                                              "Ausgabe",
      6000,            "Mietkosten",                                                                                         "Ausgabe",
      6100,            "Instandhaltung, Reparaturen und Ersatz der f\U{FC}r den Betrieb genutzten Anlagen",                  "Ausgabe",
      6105,            "Leasing bewegliche Sachanlagen",                                                                     "Ausgabe",
      6200,            "Kosten f\U{FC}r Fahrzeuge und Transport",                                                            "Ausgabe",
      6260,            "Leasing und Miete von Fahrzeugen",                                                                   "Ausgabe",
      6300,            "Versicherungen, Geb\U{FC}hren, Steuern, Genehmigungen",                                              "Ausgabe",
      6400,            "Energiekosten und Abfallentsorgung",                                                                 "Ausgabe",
      6500,            "Verwaltungskosten",                                                                                  "Ausgabe",
      6570,            "Kosten und Leasing von IT",                                                                          "Ausgabe",
      6600,            "Werbung und Marketing",                                                                              "Ausgabe",
      6700,            "Andere Betriebskosten",                                                                              "Ausgabe",
      6800,            "Abschreibung und Wertberichtigung auf bewegliche Sachanlagen",                                       "Ausgabe",
      6900,            "Finanzaufwendungen",                                                                                 "Ausgabe",
      6950,            "Finanzertr\U{E4}ge",                                                                                 "Einnahmen/Ausgabe",
      7,               "Ergebnis aus Nebent\U{E4}tigkeiten",                                                                 "Einnahmen/Ausgabe",
      7000,            "Nebenprodukte",                                                                                      "Einnahmen",
      7010,            "Nebenkosten",                                                                                        "Ausgabe",
      7500,            "Einnahmen aus Betriebsliegenschaften",                                                               "Einnahmen",
      7510,            "Kosten f\U{FC}r Betriebsliegenschaften",                                                             "Ausgabe",
      8,               "Au\U{DF}erordentliche und au\U{DF}erbetriebliche Ergebnisse",                                        "Einnahmen/Ausgabe",
      8000,            "Au\U{DF}erordentliche Kosten",                                                                       "Ausgabe",
      8100,            "Au\U{DF}erordentliche Einnahmen",                                                                    "Einnahmen",
      8500,            "Au\U{DF}erordentliche Kosten, Ausgaben oder au\U{DF}erhalb des Zeitraums",                           "Ausgabe",
      8510,            "Au\U{DF}erordentliche Einnahmen, Einnahmen oder au\U{DF}erhalb des Zeitraums",                       "Einnahmen",
      8900,            "Direkte Steuern",                                                                                    "Ausgabe",
      9,               "Abschluss",                                                                                          "Abschluss",
      91,              "Er\U{F6}ffnung",                                                                                     "Abschluss",
      9100,            "Er\U{F6}ffnungsbilanz",                                                                              "Abschluss",
      92,              "Gewinn / Verlust",                                                                                   "Abschluss",
      9200,            "Gewinn / Verlust des Gesch\U{E4}ftsjahres",                                                          "Einnahmen/Ausgabe",
    ) |>
      ensure_type(
        account_number = integer(),
        .default = character()
      )
  } else if (language == "en") {
    tibble::tribble(
      ~account_number, ~account_description,                                                               ~account_type,
      1,               "Assets",                                                                           "Asset",
      10,              "Current Assets",                                                                   "Asset",
      100,             "Cash and Cash Equivalents",                                                        "Asset",
      1000,            "Cash",                                                                             "Asset",
      1020,            "Bank",                                                                             "Asset",
      106,             "Short-term Securities Listed on Stock Exchange",                                   "Asset",
      1060,            "Securities",                                                                       "Asset",
      1069,            "Adjustment of Securities Value",                                                   "Asset",
      110,             "Trade and Other Receivables",                                                      "Asset",
      1100,            "Receivables from Deliveries and Services",                                         "Asset",
      1109,            "Doubtful Accounts",                                                                "Asset",
      1110,            "Receivables from Deliveries and Services to Group Companies",                      "Asset",
      114,             "Other Short-term Receivables",                                                     "Asset",
      1140,            "Advances and Loans",                                                               "Asset",
      1149,            "Adjustment of Advances and Loans Value",                                           "Asset",
      1170,            "Prepaid Tax: VAT on Equipment, Goods, Services, and Energy",                       "Asset",
      1171,            "Prepaid Tax: VAT on Investments and Other Operating Expenses",                     "Asset",
      1176,            "Anticipated Tax",                                                                  "Asset",
      1180,            "Receivables from Social Security and Pension Institutions",                        "Asset",
      1189,            "Withholding Tax",                                                                  "Asset",
      1190,            "Other Short-term Receivables",                                                     "Asset",
      1199,            "Adjustment of Short-term Receivables Value",                                       "Asset",
      120,             "Inventory and Unbilled Services",                                                  "Asset",
      1200,            "Commercial Goods",                                                                 "Asset",
      1210,            "Raw Materials",                                                                    "Asset",
      1220,            "Auxiliary Materials",                                                              "Asset",
      1230,            "Consumable Materials",                                                             "Asset",
      1250,            "Goods on Consignment",                                                             "Asset",
      1260,            "Finished Goods Inventory",                                                         "Asset",
      1280,            "Work in Progress",                                                                 "Asset",
      130,             "Asset Reconciliation Account",                                                     "Asset",
      1300,            "Prepaid Expenses",                                                                 "Asset",
      1301,            "Accrued Revenue",                                                                  "Asset",
      14,              "Fixed Assets",                                                                     "Asset",
      140,             "Financial Assets",                                                                 "Asset",
      1400,            "Long-term Securities",                                                             "Asset",
      1409,            "Adjustment of Securities Value",                                                   "Asset",
      1440,            "Loans",                                                                            "Asset",
      1441,            "Mortgages",                                                                        "Asset",
      1449,            "Adjustment of Long-term Receivables Value",                                        "Asset",
      148,             "Participations",                                                                   "Asset",
      1480,            "Participations",                                                                   "Asset",
      1489,            "Adjustment of Participations Value",                                               "Asset",
      150,             "Tangible Fixed Assets",                                                            "Asset",
      1500,            "Machinery and Equipment",                                                          "Asset",
      1509,            "Adjustment of Machinery and Equipment Value",                                      "Asset",
      1510,            "Furniture and Installations",                                                      "Asset",
      1519,            "Adjustment of Furniture and Installations Value",                                  "Asset",
      1520,            "Office Machines, Computers, Communication Systems",                                "Asset",
      1529,            "Adjustment of Office Machines, Computers, Communication Systems Value",            "Asset",
      1530,            "Vehicles",                                                                         "Asset",
      1539,            "Adjustment of Vehicles Value",                                                     "Asset",
      1540,            "Tools and Equipment",                                                              "Asset",
      1549,            "Adjustment of Tools and Equipment Value",                                          "Asset",
      160,             "Intangible Fixed Assets",                                                          "Asset",
      1600,            "Operating Real Estate",                                                            "Asset",
      1609,            "Adjustment of Operating Real Estate Value",                                        "Asset",
      170,             "Intangible Assets",                                                                "Asset",
      1700,            "Patents, Know-how, Licenses, Rights, Development",                                 "Asset",
      1709,            "Adjustment of Patents, Know-how, Licenses, Rights, Development Value",             "Asset",
      1770,            "Goodwill",                                                                         "Asset",
      1779,            "Adjustment of Goodwill Value",                                                     "Asset",
      180,             "Unpaid Capital: Share Capital, Foundation Capital",                                "Asset",
      1850,            "Unpaid Share Capital, Share Capital, Participation Rights, or Foundation Capital", "Asset",
      2,               "Liabilities",                                                                      "Liability",
      20,              "Short-term Liabilities",                                                           "Liability",
      200,             "Short-term Liabilities from Purchases and Services",                               "Liability",
      2000,            "Liabilities from Purchases and Service Provision (Creditors)",                     "Liability",
      2030,            "Customer Advances",                                                                "Liability",
      2050,            "Liabilities from Purchases and Services to Group Companies",                       "Liability",
      210,             "Interest-Bearing Short-term Liabilities",                                          "Liability",
      2100,            "Bank Liabilities",                                                                 "Liability",
      2120,            "Leasing Financing Commitments",                                                    "Liability",
      2140,            "Other Interest-Bearing Short-term Liabilities",                                    "Liability",
      220,             "Other Short-term Liabilities",                                                     "Liability",
      2200,            "VAT Payable",                                                                      "Liability",
      2201,            "VAT Settlement",                                                                   "Liability",
      2206,            "Due Anticipated Tax",                                                              "Liability",
      2208,            "Direct Taxes",                                                                     "Liability",
      2210,            "Other Short-term Liabilities",                                                     "Liability",
      2261,            "Dividends",                                                                        "Liability",
      2270,            "Social Security and Pension Fund Liabilities",                                     "Liability",
      2279,            "Withholding Tax",                                                                  "Liability",
      230,             "Accruals and Short-term Provisions",                                               "Liability",
      2300,            "Accrued Expenses",                                                                 "Liability",
      2301,            "Prepaid Income",                                                                   "Liability",
      2330,            "Short-term Provisions",                                                            "Liability",
      24,              "Long-term Liabilities",                                                            "Liability",
      240,             "Interest-Bearing Long-term Liabilities",                                           "Liability",
      2400,            "Bank Liabilities",                                                                 "Liability",
      2420,            "Leasing Financing Commitments",                                                    "Liability",
      2430,            "Bonds",                                                                            "Liability",
      2450,            "Loans",                                                                            "Liability",
      2451,            "Mortgages",                                                                        "Liability",
      250,             "Other Long-term Liabilities",                                                      "Liability",
      2500,            "Other Long-term Liabilities",                                                      "Liability",
      260,             "Long-term Provisions and Legal Provisions",                                        "Liability",
      2600,            "Provisions",                                                                       "Liability",
      28,              "Equity (Corporate Entities)",                                                      "Liability",
      280,             "Share Capital or Foundation Capital",                                              "Liability",
      2800,            "Share Capital, Share Capital, Foundation Capital",                                 "Liability",
      290,             "Reserves / Profits and Losses",                                                    "Liability",
      2900,            "Legal Reserves from Capital",                                                      "Liability",
      2930,            "Reserves on Own Participation Capital",                                            "Liability",
      2940,            "Evaluation Reserves",                                                              "Liability",
      2950,            "Legal Reserves from Profit",                                                       "Liability",
      2960,            "Free Reserves",                                                                    "Liability",
      2970,            "Carried Forward Profit / Loss",                                                    "Liability",
      2979,            "Current Year's Profit / Loss",                                                     "Liability",
      2980,            "Own Shares, Partner Shares, Participation Rights (Negative Entry)",                "Liability",
      2820,            "Capital Contributions / Withdrawals",                                              "Liability",
      2850,            "Private Account",                                                                  "Liability",
      2891,            "Current Year's Profit / Loss",                                                     "Liability",
      3,               "Revenue from Sales and Services",                                                  "Income",
      3000,            "Sales of Manufactured Products",                                                   "Income",
      3200,            "Sales of Goods",                                                                   "Income",
      3400,            "Sales of Services",                                                                "Income",
      3600,            "Other Sales and Service Income",                                                   "Income",
      3700,            "Own Services",                                                                     "Income",
      3710,            "Own Consumption",                                                                  "Income",
      3800,            "Sales Deductions",                                                                 "Expense",
      3805,            "Losses on Clients, Doubtful Accounts Variation",                                   "Expense",
      3900,            "Variation in Semi-Finished Goods Inventory",                                       "Income/Expense",
      3901,            "Variation in Finished Goods Inventory",                                            "Income/Expense",
      3940,            "Variation in Unbilled Services Value",                                             "Income/Expense",
      4,               "Material, Goods, and Third-Party Service Expenses",                                "Expense",
      4000,            "Material Purchases",                                                               "Expense",
      4200,            "Goods Purchases",                                                                  "Expense",
      4400,            "Third-Party Services / Works",                                                     "Expense",
      4500,            "Operating Energy Expenses",                                                        "Expense",
      4900,            "Deductions on Expenses",                                                           "Income",
      5,               "Personnel Expenses",                                                               "Expense",
      5000,            "Salaries",                                                                         "Expense",
      5700,            "Social Charges",                                                                   "Expense",
      5800,            "Other Personnel Expenses",                                                         "Expense",
      5900,            "Temporary Personnel Expenses",                                                     "Expense",
      6,               "Other Operating Expenses, Depreciation, Financial Result",                         "Expense",
      6000,            "Premises Expenses",                                                                "Expense",
      6100,            "Maintenance, Repairs, and Replacement of Operating Facilities",                    "Expense",
      6105,            "Leasing Tangible Fixed Assets",                                                    "Expense",
      6200,            "Vehicle and Transportation Expenses",                                              "Expense",
      6260,            "Leasing and Renting of Vehicles",                                                  "Expense",
      6300,            "Insurance, Rights, Taxes, Authorizations",                                         "Expense",
      6400,            "Energy and Waste Disposal Expenses",                                               "Expense",
      6500,            "Administrative Expenses",                                                          "Expense",
      6570,            "IT Expenses and Leasing",                                                          "Expense",
      6600,            "Advertising and Marketing",                                                        "Expense",
      6700,            "Other Operating Expenses",                                                         "Expense",
      6800,            "Depreciation and Value Adjustment of Tangible Fixed Assets",                       "Expense",
      6900,            "Financial Expenses",                                                               "Expense",
      6950,            "Financial Income",                                                                 "Income/Expense",
      7,               "Result from Ancillary Activities",                                                 "Income/Expense",
      7000,            "Accessories Income",                                                               "Income",
      7010,            "Accessories Expenses",                                                             "Expense",
      7500,            "Income from Operating Real Estate",                                                "Income",
      7510,            "Expenses from Operating Real Estate",                                              "Expense",
      8,               "Extraordinary and Non-operating Results",                                          "Income/Expense",
      8000,            "Non-operating Expenses",                                                           "Expense",
      8100,            "Non-operating Income",                                                             "Income",
      8500,            "Extraordinary, Exceptional, or Out-of-Period Expenses",                            "Expense",
      8510,            "Extraordinary, Exceptional, or Out-of-Period Income",                              "Income",
      8900,            "Direct Taxes",                                                                     "Expense",
      9,               "Closing",                                                                          "Closing",
      91,              "Opening",                                                                          "Closing",
      9100,            "Opening Balance",                                                                  "Closing",
      92,              "Profit / Loss",                                                                    "Closing",
      9200,            "Current Year's Profit / Loss",                                                     "Income/Expense",
    ) |>
      ensure_type(
        account_number = integer(),
        .default = character()
      )
  }
}
