# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "account_type", # <consolidate_accounting_plans>
  "account_description", # <consolidate_accounting_plans>
  "account_number", # <consolidate_accounting_plans>
  "sum_amounts", # <get_balance_accounts>
  "debit_account", # <get_account_base_category>
  "credit_account", # <get_account_base_category>
  "debit_account", # <get_high_category>
  "credit_account", # <get_high_category>
  "debit_account", # <get_intermediate_category>
  "credit_account", # <get_intermediate_category>
  "sum_amounts", # <get_income_statement>
  "account_type", # <sum_accounts>
  "amount", # <sum_accounts>
  "debit_account", # <sum_accounts>
  "credit_account", # <sum_accounts>
  "account_base_category", # <sum_accounts>
  "high_category", # <sum_accounts>
  "intermediate_category", # <sum_accounts>
  "account_number", # <sum_accounts>
  "account_description", # <sum_accounts>
  "account_number", # <select_ledger_language>
  "account_description", # <get_account_category>
  "account_type", # <get_account_category>
  "account_number", # <get_account_category>
  "account_base_category", # <get_account_category>
  "intermediate_category", # <get_account_category>
  NULL
))
